CREATE TABLE "RuntimeDocument" (
  "key" VARCHAR(191) NOT NULL,
  "value" JSONB NOT NULL,
  "createdAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT "RuntimeDocument_pkey" PRIMARY KEY ("key")
);
